// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adbpgss.proto

package org.apache.flink.connector.jdbc.table.sink.api;

public final class Adbpgss {
  private Adbpgss() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_ConnectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_ConnectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_Session_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_Session_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_InsertOption_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_InsertOption_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_UpdateOption_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_UpdateOption_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_MergeOption_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_MergeOption_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_ReadOption_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_ReadOption_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_OpenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_OpenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_DBValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_DBValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_Row_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_Row_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_RowData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_RowData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_WriteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_WriteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_ReadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_ReadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_ReadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_ReadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_TransferStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_TransferStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_CloseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_CloseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_ListSchemaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_ListSchemaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_Schema_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_Schema_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_Schemas_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_Schemas_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_ListTableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_ListTableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_DescribeTableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_DescribeTableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_TableInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_TableInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_Tables_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_Tables_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_Columns_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_Columns_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_ColumnInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_ColumnInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\radbpgss.proto\022\003api\032\033google/protobuf/em" +
      "pty.proto\032\034google/protobuf/struct.proto\032" +
      "\037google/protobuf/timestamp.proto\"l\n\016Conn" +
      "ectRequest\022\014\n\004Host\030\001 \001(\t\022\014\n\004Port\030\002 \001(\005\022\020" +
      "\n\010Username\030\003 \001(\t\022\020\n\010Password\030\004 \001(\t\022\n\n\002DB" +
      "\030\005 \001(\t\022\016\n\006UseSSL\030\006 \001(\010\"\025\n\007Session\022\n\n\002ID\030" +
      "\001 \001(\t\"s\n\014InsertOption\022\025\n\rInsertColumns\030\001" +
      " \003(\t\022\025\n\rTruncateTable\030\002 \001(\010\022\027\n\017ErrorLimi" +
      "tCount\030\004 \001(\003\022\034\n\024ErrorLimitPercentage\030\005 \001" +
      "(\005\"\205\001\n\014UpdateOption\022\024\n\014MatchColumns\030\001 \003(" +
      "\t\022\025\n\rUpdateColumns\030\002 \003(\t\022\021\n\tCondition\030\003 " +
      "\001(\t\022\027\n\017ErrorLimitCount\030\004 \001(\003\022\034\n\024ErrorLim" +
      "itPercentage\030\005 \001(\005\"\326\001\n\013MergeOption\022\025\n\rIn" +
      "sertColumns\030\001 \003(\t\022\024\n\014MatchColumns\030\002 \003(\t\022" +
      "\025\n\rUpdateColumns\030\003 \003(\t\022\021\n\tCondition\030\004 \001(" +
      "\t\022\027\n\017ErrorLimitCount\030\005 \001(\003\022\034\n\024ErrorLimit" +
      "Percentage\030\006 \001(\005\022\024\n\014SkipConflict\030\007 \001(\010\022#" +
      "\n\033EnablePrimaryKeyOnTempTable\030\010 \001(\010\"\037\n\nR" +
      "eadOption\022\021\n\tMagicCode\030\001 \001(\t\"\267\002\n\013OpenReq" +
      "uest\022\035\n\007Session\030\001 \001(\0132\014.api.Session\022\022\n\nS" +
      "chemaName\030\002 \001(\t\022\021\n\tTableName\030\003 \001(\t\022\016\n\006Pr" +
      "eSQL\030\004 \001(\t\022\017\n\007PostSQL\030\005 \001(\t\022\017\n\007Timeout\030\006" +
      " \001(\005\022\020\n\010Encoding\030\007 \001(\t\022\025\n\rStagingSchema\030" +
      "\010 \001(\t\022)\n\014InsertOption\030d \001(\0132\021.api.Insert" +
      "OptionH\000\022)\n\014UpdateOption\030e \001(\0132\021.api.Upd" +
      "ateOptionH\000\022\'\n\013MergeOption\030f \001(\0132\020.api.M" +
      "ergeOptionH\000B\010\n\006Option\"\203\002\n\007DBValue\022\024\n\nIn" +
      "t32Value\030\001 \001(\005H\000\022\024\n\nInt64Value\030\002 \001(\003H\000\022\026" +
      "\n\014Float32Value\030\005 \001(\002H\000\022\026\n\014Float64Value\030\006" +
      " \001(\001H\000\022\025\n\013StringValue\030\007 \001(\tH\000\022\024\n\nBytesVa" +
      "lue\030\010 \001(\014H\000\0224\n\016TimeStampValue\030\n \001(\0132\032.go" +
      "ogle.protobuf.TimestampH\000\022/\n\tNullValue\030\013" +
      " \001(\0162\032.google.protobuf.NullValueH\000B\010\n\006DB" +
      "Type\"$\n\003Row\022\035\n\007Columns\030\001 \003(\0132\014.api.DBVal" +
      "ue\"\027\n\007RowData\022\014\n\004Data\030\001 \001(\014\"I\n\014WriteRequ" +
      "est\022\035\n\007Session\030\001 \001(\0132\014.api.Session\022\032\n\004Ro" +
      "ws\030\002 \003(\0132\014.api.RowData\" \n\013ReadRequest\022\021\n" +
      "\tMagicCode\030\001 \001(\t\"\034\n\014ReadResponse\022\014\n\004Data" +
      "\030\001 \001(\t\"L\n\rTransferStats\022\024\n\014SuccessCount\030" +
      "\001 \001(\003\022\022\n\nErrorCount\030\002 \001(\003\022\021\n\tErrorRows\030\003" +
      " \003(\t\"R\n\014CloseRequest\022\035\n\007session\030\001 \001(\0132\014." +
      "api.Session\022\024\n\014MaxErrorRows\030\002 \001(\005\022\r\n\005Abo" +
      "rt\030\003 \001(\010\"2\n\021ListSchemaRequest\022\035\n\007Session" +
      "\030\001 \001(\0132\014.api.Session\"%\n\006Schema\022\014\n\004Name\030\001" +
      " \001(\t\022\r\n\005Owner\030\002 \001(\t\"\'\n\007Schemas\022\034\n\007Schema" +
      "s\030\001 \003(\0132\013.api.Schema\"A\n\020ListTableRequest" +
      "\022\035\n\007Session\030\001 \001(\0132\014.api.Session\022\016\n\006Schem" +
      "a\030\002 \001(\t\"\\\n\024DescribeTableRequest\022\035\n\007Sessi" +
      "on\030\001 \001(\0132\014.api.Session\022\022\n\nSchemaName\030\002 \001" +
      "(\t\022\021\n\tTableName\030\003 \001(\t\":\n\tTableInfo\022\014\n\004Na" +
      "me\030\001 \001(\t\022\037\n\004Type\030\002 \001(\0162\021.api.RelationTyp" +
      "e\"(\n\006Tables\022\036\n\006Tables\030\001 \003(\0132\016.api.TableI" +
      "nfo\"+\n\007Columns\022 \n\007Columns\030\001 \003(\0132\017.api.Co" +
      "lumnInfo\"\267\001\n\nColumnInfo\022\014\n\004Name\030\001 \001(\t\022\024\n" +
      "\014DatabaseType\030\002 \001(\t\022\021\n\tHasLength\030\003 \001(\010\022\016" +
      "\n\006Length\030\004 \001(\003\022\031\n\021HasPrecisionScale\030\005 \001(" +
      "\010\022\021\n\tPrecision\030\006 \001(\003\022\r\n\005Scale\030\007 \001(\003\022\023\n\013H" +
      "asNullable\030\010 \001(\010\022\020\n\010Nullable\030\t \001(\010*8\n\tOp" +
      "eration\022\n\n\006Insert\020\000\022\t\n\005Merge\020\001\022\n\n\006Update" +
      "\020\002\022\010\n\004Read\020\003*U\n\014RelationType\022\t\n\005Table\020\000\022" +
      "\010\n\004View\020\001\022\t\n\005Index\020\002\022\014\n\010Sequence\020\003\022\013\n\007Sp" +
      "ecial\020\004\022\n\n\005Other\020\377\0012\334\003\n\004Gpss\022.\n\007Connect\022" +
      "\023.api.ConnectRequest\032\014.api.Session\"\000\0224\n\n" +
      "Disconnect\022\014.api.Session\032\026.google.protob" +
      "uf.Empty\"\000\0222\n\004Open\022\020.api.OpenRequest\032\026.g" +
      "oogle.protobuf.Empty\"\000\0224\n\005Write\022\021.api.Wr" +
      "iteRequest\032\026.google.protobuf.Empty\"\000\0220\n\005" +
      "Close\022\021.api.CloseRequest\032\022.api.TransferS" +
      "tats\"\000\0224\n\nListSchema\022\026.api.ListSchemaReq" +
      "uest\032\014.api.Schemas\"\000\0221\n\tListTable\022\025.api." +
      "ListTableRequest\032\013.api.Tables\"\000\022:\n\rDescr" +
      "ibeTable\022\031.api.DescribeTableRequest\032\014.ap" +
      "i.Columns\"\000\022-\n\004Read\022\020.api.ReadRequest\032\021." +
      "api.ReadResponse\"\000BM\n.org.apache.flink.c" +
      "onnector.jdbc.table.sink.apiP\001Z\031adbpg_st" +
      "reaming_server/pbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_api_ConnectRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_api_ConnectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_ConnectRequest_descriptor,
        new java.lang.String[] { "Host", "Port", "Username", "Password", "DB", "UseSSL", });
    internal_static_api_Session_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_api_Session_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_Session_descriptor,
        new java.lang.String[] { "ID", });
    internal_static_api_InsertOption_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_api_InsertOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_InsertOption_descriptor,
        new java.lang.String[] { "InsertColumns", "TruncateTable", "ErrorLimitCount", "ErrorLimitPercentage", });
    internal_static_api_UpdateOption_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_api_UpdateOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_UpdateOption_descriptor,
        new java.lang.String[] { "MatchColumns", "UpdateColumns", "Condition", "ErrorLimitCount", "ErrorLimitPercentage", });
    internal_static_api_MergeOption_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_api_MergeOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_MergeOption_descriptor,
        new java.lang.String[] { "InsertColumns", "MatchColumns", "UpdateColumns", "Condition", "ErrorLimitCount", "ErrorLimitPercentage", "SkipConflict", "EnablePrimaryKeyOnTempTable", });
    internal_static_api_ReadOption_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_api_ReadOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_ReadOption_descriptor,
        new java.lang.String[] { "MagicCode", });
    internal_static_api_OpenRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_api_OpenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_OpenRequest_descriptor,
        new java.lang.String[] { "Session", "SchemaName", "TableName", "PreSQL", "PostSQL", "Timeout", "Encoding", "StagingSchema", "InsertOption", "UpdateOption", "MergeOption", "Option", });
    internal_static_api_DBValue_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_api_DBValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_DBValue_descriptor,
        new java.lang.String[] { "Int32Value", "Int64Value", "Float32Value", "Float64Value", "StringValue", "BytesValue", "TimeStampValue", "NullValue", "DBType", });
    internal_static_api_Row_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_api_Row_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_Row_descriptor,
        new java.lang.String[] { "Columns", });
    internal_static_api_RowData_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_api_RowData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_RowData_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_api_WriteRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_api_WriteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_WriteRequest_descriptor,
        new java.lang.String[] { "Session", "Rows", });
    internal_static_api_ReadRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_api_ReadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_ReadRequest_descriptor,
        new java.lang.String[] { "MagicCode", });
    internal_static_api_ReadResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_api_ReadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_ReadResponse_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_api_TransferStats_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_api_TransferStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_TransferStats_descriptor,
        new java.lang.String[] { "SuccessCount", "ErrorCount", "ErrorRows", });
    internal_static_api_CloseRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_api_CloseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_CloseRequest_descriptor,
        new java.lang.String[] { "Session", "MaxErrorRows", "Abort", });
    internal_static_api_ListSchemaRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_api_ListSchemaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_ListSchemaRequest_descriptor,
        new java.lang.String[] { "Session", });
    internal_static_api_Schema_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_api_Schema_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_Schema_descriptor,
        new java.lang.String[] { "Name", "Owner", });
    internal_static_api_Schemas_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_api_Schemas_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_Schemas_descriptor,
        new java.lang.String[] { "Schemas", });
    internal_static_api_ListTableRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_api_ListTableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_ListTableRequest_descriptor,
        new java.lang.String[] { "Session", "Schema", });
    internal_static_api_DescribeTableRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_api_DescribeTableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_DescribeTableRequest_descriptor,
        new java.lang.String[] { "Session", "SchemaName", "TableName", });
    internal_static_api_TableInfo_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_api_TableInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_TableInfo_descriptor,
        new java.lang.String[] { "Name", "Type", });
    internal_static_api_Tables_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_api_Tables_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_Tables_descriptor,
        new java.lang.String[] { "Tables", });
    internal_static_api_Columns_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_api_Columns_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_Columns_descriptor,
        new java.lang.String[] { "Columns", });
    internal_static_api_ColumnInfo_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_api_ColumnInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_ColumnInfo_descriptor,
        new java.lang.String[] { "Name", "DatabaseType", "HasLength", "Length", "HasPrecisionScale", "Precision", "Scale", "HasNullable", "Nullable", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
