// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adbpgss.proto

package org.apache.flink.connector.jdbc.table.sink.api;

/**
 * Protobuf type {@code api.ColumnInfo}
 */
public final class ColumnInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.ColumnInfo)
    ColumnInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ColumnInfo.newBuilder() to construct.
  private ColumnInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ColumnInfo() {
    name_ = "";
    databaseType_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ColumnInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.apache.flink.connector.jdbc.table.sink.api.Adbpgss.internal_static_api_ColumnInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.apache.flink.connector.jdbc.table.sink.api.Adbpgss.internal_static_api_ColumnInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo.class, org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * Column name
   * </pre>
   *
   * <code>string Name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Column name
   * </pre>
   *
   * <code>string Name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATABASETYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object databaseType_ = "";
  /**
   * <pre>
   * Greenplum data type
   * </pre>
   *
   * <code>string DatabaseType = 2;</code>
   * @return The databaseType.
   */
  @java.lang.Override
  public java.lang.String getDatabaseType() {
    java.lang.Object ref = databaseType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      databaseType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Greenplum data type
   * </pre>
   *
   * <code>string DatabaseType = 2;</code>
   * @return The bytes for databaseType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDatabaseTypeBytes() {
    java.lang.Object ref = databaseType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      databaseType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HASLENGTH_FIELD_NUMBER = 3;
  private boolean hasLength_ = false;
  /**
   * <pre>
   * Contains length information?
   * </pre>
   *
   * <code>bool HasLength = 3;</code>
   * @return The hasLength.
   */
  @java.lang.Override
  public boolean getHasLength() {
    return hasLength_;
  }

  public static final int LENGTH_FIELD_NUMBER = 4;
  private long length_ = 0L;
  /**
   * <pre>
   * Length if HasLength is true
   * </pre>
   *
   * <code>int64 Length = 4;</code>
   * @return The length.
   */
  @java.lang.Override
  public long getLength() {
    return length_;
  }

  public static final int HASPRECISIONSCALE_FIELD_NUMBER = 5;
  private boolean hasPrecisionScale_ = false;
  /**
   * <pre>
   * Contains precision or scale information?
   * </pre>
   *
   * <code>bool HasPrecisionScale = 5;</code>
   * @return The hasPrecisionScale.
   */
  @java.lang.Override
  public boolean getHasPrecisionScale() {
    return hasPrecisionScale_;
  }

  public static final int PRECISION_FIELD_NUMBER = 6;
  private long precision_ = 0L;
  /**
   * <code>int64 Precision = 6;</code>
   * @return The precision.
   */
  @java.lang.Override
  public long getPrecision() {
    return precision_;
  }

  public static final int SCALE_FIELD_NUMBER = 7;
  private long scale_ = 0L;
  /**
   * <code>int64 Scale = 7;</code>
   * @return The scale.
   */
  @java.lang.Override
  public long getScale() {
    return scale_;
  }

  public static final int HASNULLABLE_FIELD_NUMBER = 8;
  private boolean hasNullable_ = false;
  /**
   * <pre>
   * Contains Nullable constraint?
   * </pre>
   *
   * <code>bool HasNullable = 8;</code>
   * @return The hasNullable.
   */
  @java.lang.Override
  public boolean getHasNullable() {
    return hasNullable_;
  }

  public static final int NULLABLE_FIELD_NUMBER = 9;
  private boolean nullable_ = false;
  /**
   * <code>bool Nullable = 9;</code>
   * @return The nullable.
   */
  @java.lang.Override
  public boolean getNullable() {
    return nullable_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(databaseType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, databaseType_);
    }
    if (hasLength_ != false) {
      output.writeBool(3, hasLength_);
    }
    if (length_ != 0L) {
      output.writeInt64(4, length_);
    }
    if (hasPrecisionScale_ != false) {
      output.writeBool(5, hasPrecisionScale_);
    }
    if (precision_ != 0L) {
      output.writeInt64(6, precision_);
    }
    if (scale_ != 0L) {
      output.writeInt64(7, scale_);
    }
    if (hasNullable_ != false) {
      output.writeBool(8, hasNullable_);
    }
    if (nullable_ != false) {
      output.writeBool(9, nullable_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(databaseType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, databaseType_);
    }
    if (hasLength_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, hasLength_);
    }
    if (length_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, length_);
    }
    if (hasPrecisionScale_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, hasPrecisionScale_);
    }
    if (precision_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, precision_);
    }
    if (scale_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, scale_);
    }
    if (hasNullable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, hasNullable_);
    }
    if (nullable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, nullable_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo)) {
      return super.equals(obj);
    }
    org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo other = (org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getDatabaseType()
        .equals(other.getDatabaseType())) return false;
    if (getHasLength()
        != other.getHasLength()) return false;
    if (getLength()
        != other.getLength()) return false;
    if (getHasPrecisionScale()
        != other.getHasPrecisionScale()) return false;
    if (getPrecision()
        != other.getPrecision()) return false;
    if (getScale()
        != other.getScale()) return false;
    if (getHasNullable()
        != other.getHasNullable()) return false;
    if (getNullable()
        != other.getNullable()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DATABASETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getDatabaseType().hashCode();
    hash = (37 * hash) + HASLENGTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasLength());
    hash = (37 * hash) + LENGTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLength());
    hash = (37 * hash) + HASPRECISIONSCALE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasPrecisionScale());
    hash = (37 * hash) + PRECISION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPrecision());
    hash = (37 * hash) + SCALE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getScale());
    hash = (37 * hash) + HASNULLABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasNullable());
    hash = (37 * hash) + NULLABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getNullable());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.ColumnInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.ColumnInfo)
      org.apache.flink.connector.jdbc.table.sink.api.ColumnInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.flink.connector.jdbc.table.sink.api.Adbpgss.internal_static_api_ColumnInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.flink.connector.jdbc.table.sink.api.Adbpgss.internal_static_api_ColumnInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo.class, org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo.Builder.class);
    }

    // Construct using org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      databaseType_ = "";
      hasLength_ = false;
      length_ = 0L;
      hasPrecisionScale_ = false;
      precision_ = 0L;
      scale_ = 0L;
      hasNullable_ = false;
      nullable_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.apache.flink.connector.jdbc.table.sink.api.Adbpgss.internal_static_api_ColumnInfo_descriptor;
    }

    @java.lang.Override
    public org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo getDefaultInstanceForType() {
      return org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo.getDefaultInstance();
    }

    @java.lang.Override
    public org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo build() {
      org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo buildPartial() {
      org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo result = new org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.databaseType_ = databaseType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.hasLength_ = hasLength_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.length_ = length_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.hasPrecisionScale_ = hasPrecisionScale_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.precision_ = precision_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.scale_ = scale_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.hasNullable_ = hasNullable_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.nullable_ = nullable_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo) {
        return mergeFrom((org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo other) {
      if (other == org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getDatabaseType().isEmpty()) {
        databaseType_ = other.databaseType_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getHasLength() != false) {
        setHasLength(other.getHasLength());
      }
      if (other.getLength() != 0L) {
        setLength(other.getLength());
      }
      if (other.getHasPrecisionScale() != false) {
        setHasPrecisionScale(other.getHasPrecisionScale());
      }
      if (other.getPrecision() != 0L) {
        setPrecision(other.getPrecision());
      }
      if (other.getScale() != 0L) {
        setScale(other.getScale());
      }
      if (other.getHasNullable() != false) {
        setHasNullable(other.getHasNullable());
      }
      if (other.getNullable() != false) {
        setNullable(other.getNullable());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              databaseType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              hasLength_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              length_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              hasPrecisionScale_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              precision_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              scale_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              hasNullable_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              nullable_ = input.readBool();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * Column name
     * </pre>
     *
     * <code>string Name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Column name
     * </pre>
     *
     * <code>string Name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Column name
     * </pre>
     *
     * <code>string Name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Column name
     * </pre>
     *
     * <code>string Name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Column name
     * </pre>
     *
     * <code>string Name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object databaseType_ = "";
    /**
     * <pre>
     * Greenplum data type
     * </pre>
     *
     * <code>string DatabaseType = 2;</code>
     * @return The databaseType.
     */
    public java.lang.String getDatabaseType() {
      java.lang.Object ref = databaseType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        databaseType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Greenplum data type
     * </pre>
     *
     * <code>string DatabaseType = 2;</code>
     * @return The bytes for databaseType.
     */
    public com.google.protobuf.ByteString
        getDatabaseTypeBytes() {
      java.lang.Object ref = databaseType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        databaseType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Greenplum data type
     * </pre>
     *
     * <code>string DatabaseType = 2;</code>
     * @param value The databaseType to set.
     * @return This builder for chaining.
     */
    public Builder setDatabaseType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      databaseType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Greenplum data type
     * </pre>
     *
     * <code>string DatabaseType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDatabaseType() {
      databaseType_ = getDefaultInstance().getDatabaseType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Greenplum data type
     * </pre>
     *
     * <code>string DatabaseType = 2;</code>
     * @param value The bytes for databaseType to set.
     * @return This builder for chaining.
     */
    public Builder setDatabaseTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      databaseType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private boolean hasLength_ ;
    /**
     * <pre>
     * Contains length information?
     * </pre>
     *
     * <code>bool HasLength = 3;</code>
     * @return The hasLength.
     */
    @java.lang.Override
    public boolean getHasLength() {
      return hasLength_;
    }
    /**
     * <pre>
     * Contains length information?
     * </pre>
     *
     * <code>bool HasLength = 3;</code>
     * @param value The hasLength to set.
     * @return This builder for chaining.
     */
    public Builder setHasLength(boolean value) {
      
      hasLength_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contains length information?
     * </pre>
     *
     * <code>bool HasLength = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasLength() {
      bitField0_ = (bitField0_ & ~0x00000004);
      hasLength_ = false;
      onChanged();
      return this;
    }

    private long length_ ;
    /**
     * <pre>
     * Length if HasLength is true
     * </pre>
     *
     * <code>int64 Length = 4;</code>
     * @return The length.
     */
    @java.lang.Override
    public long getLength() {
      return length_;
    }
    /**
     * <pre>
     * Length if HasLength is true
     * </pre>
     *
     * <code>int64 Length = 4;</code>
     * @param value The length to set.
     * @return This builder for chaining.
     */
    public Builder setLength(long value) {
      
      length_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Length if HasLength is true
     * </pre>
     *
     * <code>int64 Length = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLength() {
      bitField0_ = (bitField0_ & ~0x00000008);
      length_ = 0L;
      onChanged();
      return this;
    }

    private boolean hasPrecisionScale_ ;
    /**
     * <pre>
     * Contains precision or scale information?
     * </pre>
     *
     * <code>bool HasPrecisionScale = 5;</code>
     * @return The hasPrecisionScale.
     */
    @java.lang.Override
    public boolean getHasPrecisionScale() {
      return hasPrecisionScale_;
    }
    /**
     * <pre>
     * Contains precision or scale information?
     * </pre>
     *
     * <code>bool HasPrecisionScale = 5;</code>
     * @param value The hasPrecisionScale to set.
     * @return This builder for chaining.
     */
    public Builder setHasPrecisionScale(boolean value) {
      
      hasPrecisionScale_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contains precision or scale information?
     * </pre>
     *
     * <code>bool HasPrecisionScale = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasPrecisionScale() {
      bitField0_ = (bitField0_ & ~0x00000010);
      hasPrecisionScale_ = false;
      onChanged();
      return this;
    }

    private long precision_ ;
    /**
     * <code>int64 Precision = 6;</code>
     * @return The precision.
     */
    @java.lang.Override
    public long getPrecision() {
      return precision_;
    }
    /**
     * <code>int64 Precision = 6;</code>
     * @param value The precision to set.
     * @return This builder for chaining.
     */
    public Builder setPrecision(long value) {
      
      precision_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 Precision = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrecision() {
      bitField0_ = (bitField0_ & ~0x00000020);
      precision_ = 0L;
      onChanged();
      return this;
    }

    private long scale_ ;
    /**
     * <code>int64 Scale = 7;</code>
     * @return The scale.
     */
    @java.lang.Override
    public long getScale() {
      return scale_;
    }
    /**
     * <code>int64 Scale = 7;</code>
     * @param value The scale to set.
     * @return This builder for chaining.
     */
    public Builder setScale(long value) {
      
      scale_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int64 Scale = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearScale() {
      bitField0_ = (bitField0_ & ~0x00000040);
      scale_ = 0L;
      onChanged();
      return this;
    }

    private boolean hasNullable_ ;
    /**
     * <pre>
     * Contains Nullable constraint?
     * </pre>
     *
     * <code>bool HasNullable = 8;</code>
     * @return The hasNullable.
     */
    @java.lang.Override
    public boolean getHasNullable() {
      return hasNullable_;
    }
    /**
     * <pre>
     * Contains Nullable constraint?
     * </pre>
     *
     * <code>bool HasNullable = 8;</code>
     * @param value The hasNullable to set.
     * @return This builder for chaining.
     */
    public Builder setHasNullable(boolean value) {
      
      hasNullable_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contains Nullable constraint?
     * </pre>
     *
     * <code>bool HasNullable = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasNullable() {
      bitField0_ = (bitField0_ & ~0x00000080);
      hasNullable_ = false;
      onChanged();
      return this;
    }

    private boolean nullable_ ;
    /**
     * <code>bool Nullable = 9;</code>
     * @return The nullable.
     */
    @java.lang.Override
    public boolean getNullable() {
      return nullable_;
    }
    /**
     * <code>bool Nullable = 9;</code>
     * @param value The nullable to set.
     * @return This builder for chaining.
     */
    public Builder setNullable(boolean value) {
      
      nullable_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>bool Nullable = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearNullable() {
      bitField0_ = (bitField0_ & ~0x00000100);
      nullable_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.ColumnInfo)
  }

  // @@protoc_insertion_point(class_scope:api.ColumnInfo)
  private static final org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo();
  }

  public static org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ColumnInfo>
      PARSER = new com.google.protobuf.AbstractParser<ColumnInfo>() {
    @java.lang.Override
    public ColumnInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ColumnInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ColumnInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.apache.flink.connector.jdbc.table.sink.api.ColumnInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

