// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package org.apache.flink.connector.jdbc.table.sink.api;

/**
 * Protobuf type {@code api.ColumnInfo}
 */
public  final class ColumnInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.ColumnInfo)
    ColumnInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ColumnInfo.newBuilder() to construct.
  private ColumnInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ColumnInfo() {
    name_ = "";
    databaseType_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ColumnInfo();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ColumnInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            databaseType_ = s;
            break;
          }
          case 24: {

            hasLength_ = input.readBool();
            break;
          }
          case 32: {

            length_ = input.readInt64();
            break;
          }
          case 40: {

            hasPrecisionScale_ = input.readBool();
            break;
          }
          case 48: {

            precision_ = input.readInt64();
            break;
          }
          case 56: {

            scale_ = input.readInt64();
            break;
          }
          case 64: {

            hasNullable_ = input.readBool();
            break;
          }
          case 72: {

            nullable_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GpssOuterClass.internal_static_api_ColumnInfo_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GpssOuterClass.internal_static_api_ColumnInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ColumnInfo.class, Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile Object name_;
  /**
   * <pre>
   * Column name
   * </pre>
   *
   * <code>string Name = 1;</code>
   * @return The name.
   */
  public String getName() {
    Object ref = name_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Column name
   * </pre>
   *
   * <code>string Name = 1;</code>
   * @return The bytes for name.
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    Object ref = name_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATABASETYPE_FIELD_NUMBER = 2;
  private volatile Object databaseType_;
  /**
   * <pre>
   * Greenplum data type
   * </pre>
   *
   * <code>string DatabaseType = 2;</code>
   * @return The databaseType.
   */
  public String getDatabaseType() {
    Object ref = databaseType_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      databaseType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Greenplum data type
   * </pre>
   *
   * <code>string DatabaseType = 2;</code>
   * @return The bytes for databaseType.
   */
  public com.google.protobuf.ByteString
      getDatabaseTypeBytes() {
    Object ref = databaseType_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      databaseType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HASLENGTH_FIELD_NUMBER = 3;
  private boolean hasLength_;
  /**
   * <pre>
   * Contains length information?
   * </pre>
   *
   * <code>bool HasLength = 3;</code>
   * @return The hasLength.
   */
  public boolean getHasLength() {
    return hasLength_;
  }

  public static final int LENGTH_FIELD_NUMBER = 4;
  private long length_;
  /**
   * <pre>
   * Length if HasLength is true
   * </pre>
   *
   * <code>int64 Length = 4;</code>
   * @return The length.
   */
  public long getLength() {
    return length_;
  }

  public static final int HASPRECISIONSCALE_FIELD_NUMBER = 5;
  private boolean hasPrecisionScale_;
  /**
   * <pre>
   * Contains precision or scale information?
   * </pre>
   *
   * <code>bool HasPrecisionScale = 5;</code>
   * @return The hasPrecisionScale.
   */
  public boolean getHasPrecisionScale() {
    return hasPrecisionScale_;
  }

  public static final int PRECISION_FIELD_NUMBER = 6;
  private long precision_;
  /**
   * <code>int64 Precision = 6;</code>
   * @return The precision.
   */
  public long getPrecision() {
    return precision_;
  }

  public static final int SCALE_FIELD_NUMBER = 7;
  private long scale_;
  /**
   * <code>int64 Scale = 7;</code>
   * @return The scale.
   */
  public long getScale() {
    return scale_;
  }

  public static final int HASNULLABLE_FIELD_NUMBER = 8;
  private boolean hasNullable_;
  /**
   * <pre>
   * Contains Nullable constraint?
   * </pre>
   *
   * <code>bool HasNullable = 8;</code>
   * @return The hasNullable.
   */
  public boolean getHasNullable() {
    return hasNullable_;
  }

  public static final int NULLABLE_FIELD_NUMBER = 9;
  private boolean nullable_;
  /**
   * <code>bool Nullable = 9;</code>
   * @return The nullable.
   */
  public boolean getNullable() {
    return nullable_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!getDatabaseTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, databaseType_);
    }
    if (hasLength_ != false) {
      output.writeBool(3, hasLength_);
    }
    if (length_ != 0L) {
      output.writeInt64(4, length_);
    }
    if (hasPrecisionScale_ != false) {
      output.writeBool(5, hasPrecisionScale_);
    }
    if (precision_ != 0L) {
      output.writeInt64(6, precision_);
    }
    if (scale_ != 0L) {
      output.writeInt64(7, scale_);
    }
    if (hasNullable_ != false) {
      output.writeBool(8, hasNullable_);
    }
    if (nullable_ != false) {
      output.writeBool(9, nullable_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!getDatabaseTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, databaseType_);
    }
    if (hasLength_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, hasLength_);
    }
    if (length_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, length_);
    }
    if (hasPrecisionScale_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, hasPrecisionScale_);
    }
    if (precision_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, precision_);
    }
    if (scale_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, scale_);
    }
    if (hasNullable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, hasNullable_);
    }
    if (nullable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, nullable_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ColumnInfo)) {
      return super.equals(obj);
    }
    ColumnInfo other = (ColumnInfo) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getDatabaseType()
        .equals(other.getDatabaseType())) return false;
    if (getHasLength()
        != other.getHasLength()) return false;
    if (getLength()
        != other.getLength()) return false;
    if (getHasPrecisionScale()
        != other.getHasPrecisionScale()) return false;
    if (getPrecision()
        != other.getPrecision()) return false;
    if (getScale()
        != other.getScale()) return false;
    if (getHasNullable()
        != other.getHasNullable()) return false;
    if (getNullable()
        != other.getNullable()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DATABASETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getDatabaseType().hashCode();
    hash = (37 * hash) + HASLENGTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasLength());
    hash = (37 * hash) + LENGTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLength());
    hash = (37 * hash) + HASPRECISIONSCALE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasPrecisionScale());
    hash = (37 * hash) + PRECISION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPrecision());
    hash = (37 * hash) + SCALE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getScale());
    hash = (37 * hash) + HASNULLABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasNullable());
    hash = (37 * hash) + NULLABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getNullable());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ColumnInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ColumnInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ColumnInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ColumnInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ColumnInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ColumnInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ColumnInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ColumnInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ColumnInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ColumnInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ColumnInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ColumnInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ColumnInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.ColumnInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.ColumnInfo)
      ColumnInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GpssOuterClass.internal_static_api_ColumnInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GpssOuterClass.internal_static_api_ColumnInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ColumnInfo.class, Builder.class);
    }

    // Construct using api.ColumnInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      name_ = "";

      databaseType_ = "";

      hasLength_ = false;

      length_ = 0L;

      hasPrecisionScale_ = false;

      precision_ = 0L;

      scale_ = 0L;

      hasNullable_ = false;

      nullable_ = false;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GpssOuterClass.internal_static_api_ColumnInfo_descriptor;
    }

    @Override
    public ColumnInfo getDefaultInstanceForType() {
      return ColumnInfo.getDefaultInstance();
    }

    @Override
    public ColumnInfo build() {
      ColumnInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ColumnInfo buildPartial() {
      ColumnInfo result = new ColumnInfo(this);
      result.name_ = name_;
      result.databaseType_ = databaseType_;
      result.hasLength_ = hasLength_;
      result.length_ = length_;
      result.hasPrecisionScale_ = hasPrecisionScale_;
      result.precision_ = precision_;
      result.scale_ = scale_;
      result.hasNullable_ = hasNullable_;
      result.nullable_ = nullable_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ColumnInfo) {
        return mergeFrom((ColumnInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ColumnInfo other) {
      if (other == ColumnInfo.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getDatabaseType().isEmpty()) {
        databaseType_ = other.databaseType_;
        onChanged();
      }
      if (other.getHasLength() != false) {
        setHasLength(other.getHasLength());
      }
      if (other.getLength() != 0L) {
        setLength(other.getLength());
      }
      if (other.getHasPrecisionScale() != false) {
        setHasPrecisionScale(other.getHasPrecisionScale());
      }
      if (other.getPrecision() != 0L) {
        setPrecision(other.getPrecision());
      }
      if (other.getScale() != 0L) {
        setScale(other.getScale());
      }
      if (other.getHasNullable() != false) {
        setHasNullable(other.getHasNullable());
      }
      if (other.getNullable() != false) {
        setNullable(other.getNullable());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ColumnInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ColumnInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object name_ = "";
    /**
     * <pre>
     * Column name
     * </pre>
     *
     * <code>string Name = 1;</code>
     * @return The name.
     */
    public String getName() {
      Object ref = name_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Column name
     * </pre>
     *
     * <code>string Name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Column name
     * </pre>
     *
     * <code>string Name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Column name
     * </pre>
     *
     * <code>string Name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Column name
     * </pre>
     *
     * <code>string Name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private Object databaseType_ = "";
    /**
     * <pre>
     * Greenplum data type
     * </pre>
     *
     * <code>string DatabaseType = 2;</code>
     * @return The databaseType.
     */
    public String getDatabaseType() {
      Object ref = databaseType_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        databaseType_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Greenplum data type
     * </pre>
     *
     * <code>string DatabaseType = 2;</code>
     * @return The bytes for databaseType.
     */
    public com.google.protobuf.ByteString
        getDatabaseTypeBytes() {
      Object ref = databaseType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        databaseType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Greenplum data type
     * </pre>
     *
     * <code>string DatabaseType = 2;</code>
     * @param value The databaseType to set.
     * @return This builder for chaining.
     */
    public Builder setDatabaseType(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      databaseType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Greenplum data type
     * </pre>
     *
     * <code>string DatabaseType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDatabaseType() {
      
      databaseType_ = getDefaultInstance().getDatabaseType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Greenplum data type
     * </pre>
     *
     * <code>string DatabaseType = 2;</code>
     * @param value The bytes for databaseType to set.
     * @return This builder for chaining.
     */
    public Builder setDatabaseTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      databaseType_ = value;
      onChanged();
      return this;
    }

    private boolean hasLength_ ;
    /**
     * <pre>
     * Contains length information?
     * </pre>
     *
     * <code>bool HasLength = 3;</code>
     * @return The hasLength.
     */
    public boolean getHasLength() {
      return hasLength_;
    }
    /**
     * <pre>
     * Contains length information?
     * </pre>
     *
     * <code>bool HasLength = 3;</code>
     * @param value The hasLength to set.
     * @return This builder for chaining.
     */
    public Builder setHasLength(boolean value) {
      
      hasLength_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contains length information?
     * </pre>
     *
     * <code>bool HasLength = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasLength() {
      
      hasLength_ = false;
      onChanged();
      return this;
    }

    private long length_ ;
    /**
     * <pre>
     * Length if HasLength is true
     * </pre>
     *
     * <code>int64 Length = 4;</code>
     * @return The length.
     */
    public long getLength() {
      return length_;
    }
    /**
     * <pre>
     * Length if HasLength is true
     * </pre>
     *
     * <code>int64 Length = 4;</code>
     * @param value The length to set.
     * @return This builder for chaining.
     */
    public Builder setLength(long value) {
      
      length_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Length if HasLength is true
     * </pre>
     *
     * <code>int64 Length = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLength() {
      
      length_ = 0L;
      onChanged();
      return this;
    }

    private boolean hasPrecisionScale_ ;
    /**
     * <pre>
     * Contains precision or scale information?
     * </pre>
     *
     * <code>bool HasPrecisionScale = 5;</code>
     * @return The hasPrecisionScale.
     */
    public boolean getHasPrecisionScale() {
      return hasPrecisionScale_;
    }
    /**
     * <pre>
     * Contains precision or scale information?
     * </pre>
     *
     * <code>bool HasPrecisionScale = 5;</code>
     * @param value The hasPrecisionScale to set.
     * @return This builder for chaining.
     */
    public Builder setHasPrecisionScale(boolean value) {
      
      hasPrecisionScale_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contains precision or scale information?
     * </pre>
     *
     * <code>bool HasPrecisionScale = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasPrecisionScale() {
      
      hasPrecisionScale_ = false;
      onChanged();
      return this;
    }

    private long precision_ ;
    /**
     * <code>int64 Precision = 6;</code>
     * @return The precision.
     */
    public long getPrecision() {
      return precision_;
    }
    /**
     * <code>int64 Precision = 6;</code>
     * @param value The precision to set.
     * @return This builder for chaining.
     */
    public Builder setPrecision(long value) {
      
      precision_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 Precision = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrecision() {
      
      precision_ = 0L;
      onChanged();
      return this;
    }

    private long scale_ ;
    /**
     * <code>int64 Scale = 7;</code>
     * @return The scale.
     */
    public long getScale() {
      return scale_;
    }
    /**
     * <code>int64 Scale = 7;</code>
     * @param value The scale to set.
     * @return This builder for chaining.
     */
    public Builder setScale(long value) {
      
      scale_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 Scale = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearScale() {
      
      scale_ = 0L;
      onChanged();
      return this;
    }

    private boolean hasNullable_ ;
    /**
     * <pre>
     * Contains Nullable constraint?
     * </pre>
     *
     * <code>bool HasNullable = 8;</code>
     * @return The hasNullable.
     */
    public boolean getHasNullable() {
      return hasNullable_;
    }
    /**
     * <pre>
     * Contains Nullable constraint?
     * </pre>
     *
     * <code>bool HasNullable = 8;</code>
     * @param value The hasNullable to set.
     * @return This builder for chaining.
     */
    public Builder setHasNullable(boolean value) {
      
      hasNullable_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contains Nullable constraint?
     * </pre>
     *
     * <code>bool HasNullable = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasNullable() {
      
      hasNullable_ = false;
      onChanged();
      return this;
    }

    private boolean nullable_ ;
    /**
     * <code>bool Nullable = 9;</code>
     * @return The nullable.
     */
    public boolean getNullable() {
      return nullable_;
    }
    /**
     * <code>bool Nullable = 9;</code>
     * @param value The nullable to set.
     * @return This builder for chaining.
     */
    public Builder setNullable(boolean value) {
      
      nullable_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool Nullable = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearNullable() {
      
      nullable_ = false;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.ColumnInfo)
  }

  // @@protoc_insertion_point(class_scope:api.ColumnInfo)
  private static final ColumnInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ColumnInfo();
  }

  public static ColumnInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ColumnInfo>
      PARSER = new com.google.protobuf.AbstractParser<ColumnInfo>() {
    @Override
    public ColumnInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ColumnInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ColumnInfo> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ColumnInfo> getParserForType() {
    return PARSER;
  }

  @Override
  public ColumnInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

