// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adbpgss.proto

package org.apache.flink.connector.jdbc.table.sink.api;

public interface DescribeTableRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.DescribeTableRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api.Session Session = 1;</code>
   * @return Whether the session field is set.
   */
  boolean hasSession();
  /**
   * <code>.api.Session Session = 1;</code>
   * @return The session.
   */
  org.apache.flink.connector.jdbc.table.sink.api.Session getSession();
  /**
   * <code>.api.Session Session = 1;</code>
   */
  org.apache.flink.connector.jdbc.table.sink.api.SessionOrBuilder getSessionOrBuilder();

  /**
   * <code>string SchemaName = 2;</code>
   * @return The schemaName.
   */
  java.lang.String getSchemaName();
  /**
   * <code>string SchemaName = 2;</code>
   * @return The bytes for schemaName.
   */
  com.google.protobuf.ByteString
      getSchemaNameBytes();

  /**
   * <code>string TableName = 3;</code>
   * @return The tableName.
   */
  java.lang.String getTableName();
  /**
   * <code>string TableName = 3;</code>
   * @return The bytes for tableName.
   */
  com.google.protobuf.ByteString
      getTableNameBytes();
}
