// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adbpgss.proto

package org.apache.flink.connector.jdbc.table.sink.api;

public interface ListTableRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.ListTableRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api.Session Session = 1;</code>
   * @return Whether the session field is set.
   */
  boolean hasSession();
  /**
   * <code>.api.Session Session = 1;</code>
   * @return The session.
   */
  org.apache.flink.connector.jdbc.table.sink.api.Session getSession();
  /**
   * <code>.api.Session Session = 1;</code>
   */
  org.apache.flink.connector.jdbc.table.sink.api.SessionOrBuilder getSessionOrBuilder();

  /**
   * <pre>
   * 'public' is the default if no Schema is provided
   * </pre>
   *
   * <code>string Schema = 2;</code>
   * @return The schema.
   */
  java.lang.String getSchema();
  /**
   * <pre>
   * 'public' is the default if no Schema is provided
   * </pre>
   *
   * <code>string Schema = 2;</code>
   * @return The bytes for schema.
   */
  com.google.protobuf.ByteString
      getSchemaBytes();
}
