// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package org.apache.flink.connector.jdbc.table.sink.api;

public interface ListTableRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.ListTableRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api.Session Session = 1;</code>
   * @return Whether the session field is set.
   */
  boolean hasSession();
  /**
   * <code>.api.Session Session = 1;</code>
   * @return The session.
   */
  Session getSession();
  /**
   * <code>.api.Session Session = 1;</code>
   */
  SessionOrBuilder getSessionOrBuilder();

  /**
   * <pre>
   * 'public' is the default if no Schema is provided
   * </pre>
   *
   * <code>string Schema = 2;</code>
   * @return The schema.
   */
  String getSchema();
  /**
   * <pre>
   * 'public' is the default if no Schema is provided
   * </pre>
   *
   * <code>string Schema = 2;</code>
   * @return The bytes for schema.
   */
  com.google.protobuf.ByteString
      getSchemaBytes();
}
