// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adbpgss.proto

package org.apache.flink.connector.jdbc.table.sink.api;

/**
 * <pre>
 * Open service Request message
 * </pre>
 *
 * Protobuf type {@code api.OpenRequest}
 */
public final class OpenRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.OpenRequest)
    OpenRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OpenRequest.newBuilder() to construct.
  private OpenRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OpenRequest() {
    schemaName_ = "";
    tableName_ = "";
    preSQL_ = "";
    postSQL_ = "";
    encoding_ = "";
    stagingSchema_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OpenRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.apache.flink.connector.jdbc.table.sink.api.Adbpgss.internal_static_api_OpenRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.apache.flink.connector.jdbc.table.sink.api.Adbpgss.internal_static_api_OpenRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.apache.flink.connector.jdbc.table.sink.api.OpenRequest.class, org.apache.flink.connector.jdbc.table.sink.api.OpenRequest.Builder.class);
  }

  private int optionCase_ = 0;
  private java.lang.Object option_;
  public enum OptionCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    INSERTOPTION(100),
    UPDATEOPTION(101),
    MERGEOPTION(102),
    OPTION_NOT_SET(0);
    private final int value;
    private OptionCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OptionCase valueOf(int value) {
      return forNumber(value);
    }

    public static OptionCase forNumber(int value) {
      switch (value) {
        case 100: return INSERTOPTION;
        case 101: return UPDATEOPTION;
        case 102: return MERGEOPTION;
        case 0: return OPTION_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public OptionCase
  getOptionCase() {
    return OptionCase.forNumber(
        optionCase_);
  }

  public static final int SESSION_FIELD_NUMBER = 1;
  private org.apache.flink.connector.jdbc.table.sink.api.Session session_;
  /**
   * <pre>
   * Session ID returned by Connect
   * </pre>
   *
   * <code>.api.Session Session = 1;</code>
   * @return Whether the session field is set.
   */
  @java.lang.Override
  public boolean hasSession() {
    return session_ != null;
  }
  /**
   * <pre>
   * Session ID returned by Connect
   * </pre>
   *
   * <code>.api.Session Session = 1;</code>
   * @return The session.
   */
  @java.lang.Override
  public org.apache.flink.connector.jdbc.table.sink.api.Session getSession() {
    return session_ == null ? org.apache.flink.connector.jdbc.table.sink.api.Session.getDefaultInstance() : session_;
  }
  /**
   * <pre>
   * Session ID returned by Connect
   * </pre>
   *
   * <code>.api.Session Session = 1;</code>
   */
  @java.lang.Override
  public org.apache.flink.connector.jdbc.table.sink.api.SessionOrBuilder getSessionOrBuilder() {
    return session_ == null ? org.apache.flink.connector.jdbc.table.sink.api.Session.getDefaultInstance() : session_;
  }

  public static final int SCHEMANAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object schemaName_ = "";
  /**
   * <pre>
   * Name of the Greenplum Database schema
   * </pre>
   *
   * <code>string SchemaName = 2;</code>
   * @return The schemaName.
   */
  @java.lang.Override
  public java.lang.String getSchemaName() {
    java.lang.Object ref = schemaName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      schemaName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of the Greenplum Database schema
   * </pre>
   *
   * <code>string SchemaName = 2;</code>
   * @return The bytes for schemaName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSchemaNameBytes() {
    java.lang.Object ref = schemaName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      schemaName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TABLENAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tableName_ = "";
  /**
   * <pre>
   * Name of the Greenplum Database table
   * </pre>
   *
   * <code>string TableName = 3;</code>
   * @return The tableName.
   */
  @java.lang.Override
  public java.lang.String getTableName() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tableName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of the Greenplum Database table
   * </pre>
   *
   * <code>string TableName = 3;</code>
   * @return The bytes for tableName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTableNameBytes() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tableName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRESQL_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object preSQL_ = "";
  /**
   * <pre>
   * SQL to execute before gpss loads the data
   * </pre>
   *
   * <code>string PreSQL = 4;</code>
   * @return The preSQL.
   */
  @java.lang.Override
  public java.lang.String getPreSQL() {
    java.lang.Object ref = preSQL_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      preSQL_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * SQL to execute before gpss loads the data
   * </pre>
   *
   * <code>string PreSQL = 4;</code>
   * @return The bytes for preSQL.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPreSQLBytes() {
    java.lang.Object ref = preSQL_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      preSQL_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSTSQL_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object postSQL_ = "";
  /**
   * <pre>
   * SQL to execute after gpss loads the data
   * </pre>
   *
   * <code>string PostSQL = 5;</code>
   * @return The postSQL.
   */
  @java.lang.Override
  public java.lang.String getPostSQL() {
    java.lang.Object ref = postSQL_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      postSQL_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * SQL to execute after gpss loads the data
   * </pre>
   *
   * <code>string PostSQL = 5;</code>
   * @return The bytes for postSQL.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPostSQLBytes() {
    java.lang.Object ref = postSQL_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      postSQL_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMEOUT_FIELD_NUMBER = 6;
  private int timeout_ = 0;
  /**
   * <pre>
   * Time to wait before aborting the operation (seconds); not supported
   * </pre>
   *
   * <code>int32 Timeout = 6;</code>
   * @return The timeout.
   */
  @java.lang.Override
  public int getTimeout() {
    return timeout_;
  }

  public static final int ENCODING_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object encoding_ = "";
  /**
   * <pre>
   * Encoding of text data; not supported
   * </pre>
   *
   * <code>string Encoding = 7;</code>
   * @return The encoding.
   */
  @java.lang.Override
  public java.lang.String getEncoding() {
    java.lang.Object ref = encoding_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      encoding_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Encoding of text data; not supported
   * </pre>
   *
   * <code>string Encoding = 7;</code>
   * @return The bytes for encoding.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEncodingBytes() {
    java.lang.Object ref = encoding_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      encoding_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STAGINGSCHEMA_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object stagingSchema_ = "";
  /**
   * <pre>
   * Schema in which gpss creates external and temp tables; default is to create these tables in the same schema as the target table
   * </pre>
   *
   * <code>string StagingSchema = 8;</code>
   * @return The stagingSchema.
   */
  @java.lang.Override
  public java.lang.String getStagingSchema() {
    java.lang.Object ref = stagingSchema_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stagingSchema_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Schema in which gpss creates external and temp tables; default is to create these tables in the same schema as the target table
   * </pre>
   *
   * <code>string StagingSchema = 8;</code>
   * @return The bytes for stagingSchema.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStagingSchemaBytes() {
    java.lang.Object ref = stagingSchema_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stagingSchema_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INSERTOPTION_FIELD_NUMBER = 100;
  /**
   * <code>.api.InsertOption InsertOption = 100;</code>
   * @return Whether the insertOption field is set.
   */
  @java.lang.Override
  public boolean hasInsertOption() {
    return optionCase_ == 100;
  }
  /**
   * <code>.api.InsertOption InsertOption = 100;</code>
   * @return The insertOption.
   */
  @java.lang.Override
  public org.apache.flink.connector.jdbc.table.sink.api.InsertOption getInsertOption() {
    if (optionCase_ == 100) {
       return (org.apache.flink.connector.jdbc.table.sink.api.InsertOption) option_;
    }
    return org.apache.flink.connector.jdbc.table.sink.api.InsertOption.getDefaultInstance();
  }
  /**
   * <code>.api.InsertOption InsertOption = 100;</code>
   */
  @java.lang.Override
  public org.apache.flink.connector.jdbc.table.sink.api.InsertOptionOrBuilder getInsertOptionOrBuilder() {
    if (optionCase_ == 100) {
       return (org.apache.flink.connector.jdbc.table.sink.api.InsertOption) option_;
    }
    return org.apache.flink.connector.jdbc.table.sink.api.InsertOption.getDefaultInstance();
  }

  public static final int UPDATEOPTION_FIELD_NUMBER = 101;
  /**
   * <code>.api.UpdateOption UpdateOption = 101;</code>
   * @return Whether the updateOption field is set.
   */
  @java.lang.Override
  public boolean hasUpdateOption() {
    return optionCase_ == 101;
  }
  /**
   * <code>.api.UpdateOption UpdateOption = 101;</code>
   * @return The updateOption.
   */
  @java.lang.Override
  public org.apache.flink.connector.jdbc.table.sink.api.UpdateOption getUpdateOption() {
    if (optionCase_ == 101) {
       return (org.apache.flink.connector.jdbc.table.sink.api.UpdateOption) option_;
    }
    return org.apache.flink.connector.jdbc.table.sink.api.UpdateOption.getDefaultInstance();
  }
  /**
   * <code>.api.UpdateOption UpdateOption = 101;</code>
   */
  @java.lang.Override
  public org.apache.flink.connector.jdbc.table.sink.api.UpdateOptionOrBuilder getUpdateOptionOrBuilder() {
    if (optionCase_ == 101) {
       return (org.apache.flink.connector.jdbc.table.sink.api.UpdateOption) option_;
    }
    return org.apache.flink.connector.jdbc.table.sink.api.UpdateOption.getDefaultInstance();
  }

  public static final int MERGEOPTION_FIELD_NUMBER = 102;
  /**
   * <code>.api.MergeOption MergeOption = 102;</code>
   * @return Whether the mergeOption field is set.
   */
  @java.lang.Override
  public boolean hasMergeOption() {
    return optionCase_ == 102;
  }
  /**
   * <code>.api.MergeOption MergeOption = 102;</code>
   * @return The mergeOption.
   */
  @java.lang.Override
  public org.apache.flink.connector.jdbc.table.sink.api.MergeOption getMergeOption() {
    if (optionCase_ == 102) {
       return (org.apache.flink.connector.jdbc.table.sink.api.MergeOption) option_;
    }
    return org.apache.flink.connector.jdbc.table.sink.api.MergeOption.getDefaultInstance();
  }
  /**
   * <code>.api.MergeOption MergeOption = 102;</code>
   */
  @java.lang.Override
  public org.apache.flink.connector.jdbc.table.sink.api.MergeOptionOrBuilder getMergeOptionOrBuilder() {
    if (optionCase_ == 102) {
       return (org.apache.flink.connector.jdbc.table.sink.api.MergeOption) option_;
    }
    return org.apache.flink.connector.jdbc.table.sink.api.MergeOption.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (session_ != null) {
      output.writeMessage(1, getSession());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(schemaName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, schemaName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tableName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, tableName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(preSQL_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, preSQL_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(postSQL_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, postSQL_);
    }
    if (timeout_ != 0) {
      output.writeInt32(6, timeout_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(encoding_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, encoding_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stagingSchema_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, stagingSchema_);
    }
    if (optionCase_ == 100) {
      output.writeMessage(100, (org.apache.flink.connector.jdbc.table.sink.api.InsertOption) option_);
    }
    if (optionCase_ == 101) {
      output.writeMessage(101, (org.apache.flink.connector.jdbc.table.sink.api.UpdateOption) option_);
    }
    if (optionCase_ == 102) {
      output.writeMessage(102, (org.apache.flink.connector.jdbc.table.sink.api.MergeOption) option_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (session_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSession());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(schemaName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, schemaName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tableName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, tableName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(preSQL_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, preSQL_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(postSQL_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, postSQL_);
    }
    if (timeout_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, timeout_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(encoding_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, encoding_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stagingSchema_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, stagingSchema_);
    }
    if (optionCase_ == 100) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(100, (org.apache.flink.connector.jdbc.table.sink.api.InsertOption) option_);
    }
    if (optionCase_ == 101) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(101, (org.apache.flink.connector.jdbc.table.sink.api.UpdateOption) option_);
    }
    if (optionCase_ == 102) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(102, (org.apache.flink.connector.jdbc.table.sink.api.MergeOption) option_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.apache.flink.connector.jdbc.table.sink.api.OpenRequest)) {
      return super.equals(obj);
    }
    org.apache.flink.connector.jdbc.table.sink.api.OpenRequest other = (org.apache.flink.connector.jdbc.table.sink.api.OpenRequest) obj;

    if (hasSession() != other.hasSession()) return false;
    if (hasSession()) {
      if (!getSession()
          .equals(other.getSession())) return false;
    }
    if (!getSchemaName()
        .equals(other.getSchemaName())) return false;
    if (!getTableName()
        .equals(other.getTableName())) return false;
    if (!getPreSQL()
        .equals(other.getPreSQL())) return false;
    if (!getPostSQL()
        .equals(other.getPostSQL())) return false;
    if (getTimeout()
        != other.getTimeout()) return false;
    if (!getEncoding()
        .equals(other.getEncoding())) return false;
    if (!getStagingSchema()
        .equals(other.getStagingSchema())) return false;
    if (!getOptionCase().equals(other.getOptionCase())) return false;
    switch (optionCase_) {
      case 100:
        if (!getInsertOption()
            .equals(other.getInsertOption())) return false;
        break;
      case 101:
        if (!getUpdateOption()
            .equals(other.getUpdateOption())) return false;
        break;
      case 102:
        if (!getMergeOption()
            .equals(other.getMergeOption())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSession()) {
      hash = (37 * hash) + SESSION_FIELD_NUMBER;
      hash = (53 * hash) + getSession().hashCode();
    }
    hash = (37 * hash) + SCHEMANAME_FIELD_NUMBER;
    hash = (53 * hash) + getSchemaName().hashCode();
    hash = (37 * hash) + TABLENAME_FIELD_NUMBER;
    hash = (53 * hash) + getTableName().hashCode();
    hash = (37 * hash) + PRESQL_FIELD_NUMBER;
    hash = (53 * hash) + getPreSQL().hashCode();
    hash = (37 * hash) + POSTSQL_FIELD_NUMBER;
    hash = (53 * hash) + getPostSQL().hashCode();
    hash = (37 * hash) + TIMEOUT_FIELD_NUMBER;
    hash = (53 * hash) + getTimeout();
    hash = (37 * hash) + ENCODING_FIELD_NUMBER;
    hash = (53 * hash) + getEncoding().hashCode();
    hash = (37 * hash) + STAGINGSCHEMA_FIELD_NUMBER;
    hash = (53 * hash) + getStagingSchema().hashCode();
    switch (optionCase_) {
      case 100:
        hash = (37 * hash) + INSERTOPTION_FIELD_NUMBER;
        hash = (53 * hash) + getInsertOption().hashCode();
        break;
      case 101:
        hash = (37 * hash) + UPDATEOPTION_FIELD_NUMBER;
        hash = (53 * hash) + getUpdateOption().hashCode();
        break;
      case 102:
        hash = (37 * hash) + MERGEOPTION_FIELD_NUMBER;
        hash = (53 * hash) + getMergeOption().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.apache.flink.connector.jdbc.table.sink.api.OpenRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.flink.connector.jdbc.table.sink.api.OpenRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.flink.connector.jdbc.table.sink.api.OpenRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.flink.connector.jdbc.table.sink.api.OpenRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.flink.connector.jdbc.table.sink.api.OpenRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.flink.connector.jdbc.table.sink.api.OpenRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.flink.connector.jdbc.table.sink.api.OpenRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.flink.connector.jdbc.table.sink.api.OpenRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.flink.connector.jdbc.table.sink.api.OpenRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.apache.flink.connector.jdbc.table.sink.api.OpenRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.flink.connector.jdbc.table.sink.api.OpenRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.flink.connector.jdbc.table.sink.api.OpenRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.apache.flink.connector.jdbc.table.sink.api.OpenRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Open service Request message
   * </pre>
   *
   * Protobuf type {@code api.OpenRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.OpenRequest)
      org.apache.flink.connector.jdbc.table.sink.api.OpenRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.flink.connector.jdbc.table.sink.api.Adbpgss.internal_static_api_OpenRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.flink.connector.jdbc.table.sink.api.Adbpgss.internal_static_api_OpenRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.flink.connector.jdbc.table.sink.api.OpenRequest.class, org.apache.flink.connector.jdbc.table.sink.api.OpenRequest.Builder.class);
    }

    // Construct using org.apache.flink.connector.jdbc.table.sink.api.OpenRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      session_ = null;
      if (sessionBuilder_ != null) {
        sessionBuilder_.dispose();
        sessionBuilder_ = null;
      }
      schemaName_ = "";
      tableName_ = "";
      preSQL_ = "";
      postSQL_ = "";
      timeout_ = 0;
      encoding_ = "";
      stagingSchema_ = "";
      if (insertOptionBuilder_ != null) {
        insertOptionBuilder_.clear();
      }
      if (updateOptionBuilder_ != null) {
        updateOptionBuilder_.clear();
      }
      if (mergeOptionBuilder_ != null) {
        mergeOptionBuilder_.clear();
      }
      optionCase_ = 0;
      option_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.apache.flink.connector.jdbc.table.sink.api.Adbpgss.internal_static_api_OpenRequest_descriptor;
    }

    @java.lang.Override
    public org.apache.flink.connector.jdbc.table.sink.api.OpenRequest getDefaultInstanceForType() {
      return org.apache.flink.connector.jdbc.table.sink.api.OpenRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.apache.flink.connector.jdbc.table.sink.api.OpenRequest build() {
      org.apache.flink.connector.jdbc.table.sink.api.OpenRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.apache.flink.connector.jdbc.table.sink.api.OpenRequest buildPartial() {
      org.apache.flink.connector.jdbc.table.sink.api.OpenRequest result = new org.apache.flink.connector.jdbc.table.sink.api.OpenRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(org.apache.flink.connector.jdbc.table.sink.api.OpenRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.session_ = sessionBuilder_ == null
            ? session_
            : sessionBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.schemaName_ = schemaName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.tableName_ = tableName_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.preSQL_ = preSQL_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.postSQL_ = postSQL_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.timeout_ = timeout_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.encoding_ = encoding_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.stagingSchema_ = stagingSchema_;
      }
    }

    private void buildPartialOneofs(org.apache.flink.connector.jdbc.table.sink.api.OpenRequest result) {
      result.optionCase_ = optionCase_;
      result.option_ = this.option_;
      if (optionCase_ == 100 &&
          insertOptionBuilder_ != null) {
        result.option_ = insertOptionBuilder_.build();
      }
      if (optionCase_ == 101 &&
          updateOptionBuilder_ != null) {
        result.option_ = updateOptionBuilder_.build();
      }
      if (optionCase_ == 102 &&
          mergeOptionBuilder_ != null) {
        result.option_ = mergeOptionBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.apache.flink.connector.jdbc.table.sink.api.OpenRequest) {
        return mergeFrom((org.apache.flink.connector.jdbc.table.sink.api.OpenRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.apache.flink.connector.jdbc.table.sink.api.OpenRequest other) {
      if (other == org.apache.flink.connector.jdbc.table.sink.api.OpenRequest.getDefaultInstance()) return this;
      if (other.hasSession()) {
        mergeSession(other.getSession());
      }
      if (!other.getSchemaName().isEmpty()) {
        schemaName_ = other.schemaName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getTableName().isEmpty()) {
        tableName_ = other.tableName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getPreSQL().isEmpty()) {
        preSQL_ = other.preSQL_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getPostSQL().isEmpty()) {
        postSQL_ = other.postSQL_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getTimeout() != 0) {
        setTimeout(other.getTimeout());
      }
      if (!other.getEncoding().isEmpty()) {
        encoding_ = other.encoding_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getStagingSchema().isEmpty()) {
        stagingSchema_ = other.stagingSchema_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      switch (other.getOptionCase()) {
        case INSERTOPTION: {
          mergeInsertOption(other.getInsertOption());
          break;
        }
        case UPDATEOPTION: {
          mergeUpdateOption(other.getUpdateOption());
          break;
        }
        case MERGEOPTION: {
          mergeMergeOption(other.getMergeOption());
          break;
        }
        case OPTION_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getSessionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              schemaName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              tableName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              preSQL_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              postSQL_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              timeout_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              encoding_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              stagingSchema_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 802: {
              input.readMessage(
                  getInsertOptionFieldBuilder().getBuilder(),
                  extensionRegistry);
              optionCase_ = 100;
              break;
            } // case 802
            case 810: {
              input.readMessage(
                  getUpdateOptionFieldBuilder().getBuilder(),
                  extensionRegistry);
              optionCase_ = 101;
              break;
            } // case 810
            case 818: {
              input.readMessage(
                  getMergeOptionFieldBuilder().getBuilder(),
                  extensionRegistry);
              optionCase_ = 102;
              break;
            } // case 818
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int optionCase_ = 0;
    private java.lang.Object option_;
    public OptionCase
        getOptionCase() {
      return OptionCase.forNumber(
          optionCase_);
    }

    public Builder clearOption() {
      optionCase_ = 0;
      option_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private org.apache.flink.connector.jdbc.table.sink.api.Session session_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.flink.connector.jdbc.table.sink.api.Session, org.apache.flink.connector.jdbc.table.sink.api.Session.Builder, org.apache.flink.connector.jdbc.table.sink.api.SessionOrBuilder> sessionBuilder_;
    /**
     * <pre>
     * Session ID returned by Connect
     * </pre>
     *
     * <code>.api.Session Session = 1;</code>
     * @return Whether the session field is set.
     */
    public boolean hasSession() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Session ID returned by Connect
     * </pre>
     *
     * <code>.api.Session Session = 1;</code>
     * @return The session.
     */
    public org.apache.flink.connector.jdbc.table.sink.api.Session getSession() {
      if (sessionBuilder_ == null) {
        return session_ == null ? org.apache.flink.connector.jdbc.table.sink.api.Session.getDefaultInstance() : session_;
      } else {
        return sessionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Session ID returned by Connect
     * </pre>
     *
     * <code>.api.Session Session = 1;</code>
     */
    public Builder setSession(org.apache.flink.connector.jdbc.table.sink.api.Session value) {
      if (sessionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        session_ = value;
      } else {
        sessionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Session ID returned by Connect
     * </pre>
     *
     * <code>.api.Session Session = 1;</code>
     */
    public Builder setSession(
        org.apache.flink.connector.jdbc.table.sink.api.Session.Builder builderForValue) {
      if (sessionBuilder_ == null) {
        session_ = builderForValue.build();
      } else {
        sessionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Session ID returned by Connect
     * </pre>
     *
     * <code>.api.Session Session = 1;</code>
     */
    public Builder mergeSession(org.apache.flink.connector.jdbc.table.sink.api.Session value) {
      if (sessionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          session_ != null &&
          session_ != org.apache.flink.connector.jdbc.table.sink.api.Session.getDefaultInstance()) {
          getSessionBuilder().mergeFrom(value);
        } else {
          session_ = value;
        }
      } else {
        sessionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Session ID returned by Connect
     * </pre>
     *
     * <code>.api.Session Session = 1;</code>
     */
    public Builder clearSession() {
      bitField0_ = (bitField0_ & ~0x00000001);
      session_ = null;
      if (sessionBuilder_ != null) {
        sessionBuilder_.dispose();
        sessionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Session ID returned by Connect
     * </pre>
     *
     * <code>.api.Session Session = 1;</code>
     */
    public org.apache.flink.connector.jdbc.table.sink.api.Session.Builder getSessionBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getSessionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Session ID returned by Connect
     * </pre>
     *
     * <code>.api.Session Session = 1;</code>
     */
    public org.apache.flink.connector.jdbc.table.sink.api.SessionOrBuilder getSessionOrBuilder() {
      if (sessionBuilder_ != null) {
        return sessionBuilder_.getMessageOrBuilder();
      } else {
        return session_ == null ?
            org.apache.flink.connector.jdbc.table.sink.api.Session.getDefaultInstance() : session_;
      }
    }
    /**
     * <pre>
     * Session ID returned by Connect
     * </pre>
     *
     * <code>.api.Session Session = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.flink.connector.jdbc.table.sink.api.Session, org.apache.flink.connector.jdbc.table.sink.api.Session.Builder, org.apache.flink.connector.jdbc.table.sink.api.SessionOrBuilder> 
        getSessionFieldBuilder() {
      if (sessionBuilder_ == null) {
        sessionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.apache.flink.connector.jdbc.table.sink.api.Session, org.apache.flink.connector.jdbc.table.sink.api.Session.Builder, org.apache.flink.connector.jdbc.table.sink.api.SessionOrBuilder>(
                getSession(),
                getParentForChildren(),
                isClean());
        session_ = null;
      }
      return sessionBuilder_;
    }

    private java.lang.Object schemaName_ = "";
    /**
     * <pre>
     * Name of the Greenplum Database schema
     * </pre>
     *
     * <code>string SchemaName = 2;</code>
     * @return The schemaName.
     */
    public java.lang.String getSchemaName() {
      java.lang.Object ref = schemaName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schemaName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of the Greenplum Database schema
     * </pre>
     *
     * <code>string SchemaName = 2;</code>
     * @return The bytes for schemaName.
     */
    public com.google.protobuf.ByteString
        getSchemaNameBytes() {
      java.lang.Object ref = schemaName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schemaName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of the Greenplum Database schema
     * </pre>
     *
     * <code>string SchemaName = 2;</code>
     * @param value The schemaName to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      schemaName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the Greenplum Database schema
     * </pre>
     *
     * <code>string SchemaName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSchemaName() {
      schemaName_ = getDefaultInstance().getSchemaName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the Greenplum Database schema
     * </pre>
     *
     * <code>string SchemaName = 2;</code>
     * @param value The bytes for schemaName to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      schemaName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object tableName_ = "";
    /**
     * <pre>
     * Name of the Greenplum Database table
     * </pre>
     *
     * <code>string TableName = 3;</code>
     * @return The tableName.
     */
    public java.lang.String getTableName() {
      java.lang.Object ref = tableName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of the Greenplum Database table
     * </pre>
     *
     * <code>string TableName = 3;</code>
     * @return The bytes for tableName.
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      java.lang.Object ref = tableName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of the Greenplum Database table
     * </pre>
     *
     * <code>string TableName = 3;</code>
     * @param value The tableName to set.
     * @return This builder for chaining.
     */
    public Builder setTableName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tableName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the Greenplum Database table
     * </pre>
     *
     * <code>string TableName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTableName() {
      tableName_ = getDefaultInstance().getTableName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the Greenplum Database table
     * </pre>
     *
     * <code>string TableName = 3;</code>
     * @param value The bytes for tableName to set.
     * @return This builder for chaining.
     */
    public Builder setTableNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tableName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object preSQL_ = "";
    /**
     * <pre>
     * SQL to execute before gpss loads the data
     * </pre>
     *
     * <code>string PreSQL = 4;</code>
     * @return The preSQL.
     */
    public java.lang.String getPreSQL() {
      java.lang.Object ref = preSQL_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        preSQL_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * SQL to execute before gpss loads the data
     * </pre>
     *
     * <code>string PreSQL = 4;</code>
     * @return The bytes for preSQL.
     */
    public com.google.protobuf.ByteString
        getPreSQLBytes() {
      java.lang.Object ref = preSQL_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        preSQL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * SQL to execute before gpss loads the data
     * </pre>
     *
     * <code>string PreSQL = 4;</code>
     * @param value The preSQL to set.
     * @return This builder for chaining.
     */
    public Builder setPreSQL(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      preSQL_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * SQL to execute before gpss loads the data
     * </pre>
     *
     * <code>string PreSQL = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPreSQL() {
      preSQL_ = getDefaultInstance().getPreSQL();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * SQL to execute before gpss loads the data
     * </pre>
     *
     * <code>string PreSQL = 4;</code>
     * @param value The bytes for preSQL to set.
     * @return This builder for chaining.
     */
    public Builder setPreSQLBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      preSQL_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object postSQL_ = "";
    /**
     * <pre>
     * SQL to execute after gpss loads the data
     * </pre>
     *
     * <code>string PostSQL = 5;</code>
     * @return The postSQL.
     */
    public java.lang.String getPostSQL() {
      java.lang.Object ref = postSQL_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        postSQL_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * SQL to execute after gpss loads the data
     * </pre>
     *
     * <code>string PostSQL = 5;</code>
     * @return The bytes for postSQL.
     */
    public com.google.protobuf.ByteString
        getPostSQLBytes() {
      java.lang.Object ref = postSQL_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        postSQL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * SQL to execute after gpss loads the data
     * </pre>
     *
     * <code>string PostSQL = 5;</code>
     * @param value The postSQL to set.
     * @return This builder for chaining.
     */
    public Builder setPostSQL(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      postSQL_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * SQL to execute after gpss loads the data
     * </pre>
     *
     * <code>string PostSQL = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPostSQL() {
      postSQL_ = getDefaultInstance().getPostSQL();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * SQL to execute after gpss loads the data
     * </pre>
     *
     * <code>string PostSQL = 5;</code>
     * @param value The bytes for postSQL to set.
     * @return This builder for chaining.
     */
    public Builder setPostSQLBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      postSQL_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private int timeout_ ;
    /**
     * <pre>
     * Time to wait before aborting the operation (seconds); not supported
     * </pre>
     *
     * <code>int32 Timeout = 6;</code>
     * @return The timeout.
     */
    @java.lang.Override
    public int getTimeout() {
      return timeout_;
    }
    /**
     * <pre>
     * Time to wait before aborting the operation (seconds); not supported
     * </pre>
     *
     * <code>int32 Timeout = 6;</code>
     * @param value The timeout to set.
     * @return This builder for chaining.
     */
    public Builder setTimeout(int value) {
      
      timeout_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Time to wait before aborting the operation (seconds); not supported
     * </pre>
     *
     * <code>int32 Timeout = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeout() {
      bitField0_ = (bitField0_ & ~0x00000020);
      timeout_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object encoding_ = "";
    /**
     * <pre>
     * Encoding of text data; not supported
     * </pre>
     *
     * <code>string Encoding = 7;</code>
     * @return The encoding.
     */
    public java.lang.String getEncoding() {
      java.lang.Object ref = encoding_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        encoding_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Encoding of text data; not supported
     * </pre>
     *
     * <code>string Encoding = 7;</code>
     * @return The bytes for encoding.
     */
    public com.google.protobuf.ByteString
        getEncodingBytes() {
      java.lang.Object ref = encoding_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        encoding_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Encoding of text data; not supported
     * </pre>
     *
     * <code>string Encoding = 7;</code>
     * @param value The encoding to set.
     * @return This builder for chaining.
     */
    public Builder setEncoding(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      encoding_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Encoding of text data; not supported
     * </pre>
     *
     * <code>string Encoding = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncoding() {
      encoding_ = getDefaultInstance().getEncoding();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Encoding of text data; not supported
     * </pre>
     *
     * <code>string Encoding = 7;</code>
     * @param value The bytes for encoding to set.
     * @return This builder for chaining.
     */
    public Builder setEncodingBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      encoding_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object stagingSchema_ = "";
    /**
     * <pre>
     * Schema in which gpss creates external and temp tables; default is to create these tables in the same schema as the target table
     * </pre>
     *
     * <code>string StagingSchema = 8;</code>
     * @return The stagingSchema.
     */
    public java.lang.String getStagingSchema() {
      java.lang.Object ref = stagingSchema_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stagingSchema_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Schema in which gpss creates external and temp tables; default is to create these tables in the same schema as the target table
     * </pre>
     *
     * <code>string StagingSchema = 8;</code>
     * @return The bytes for stagingSchema.
     */
    public com.google.protobuf.ByteString
        getStagingSchemaBytes() {
      java.lang.Object ref = stagingSchema_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stagingSchema_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Schema in which gpss creates external and temp tables; default is to create these tables in the same schema as the target table
     * </pre>
     *
     * <code>string StagingSchema = 8;</code>
     * @param value The stagingSchema to set.
     * @return This builder for chaining.
     */
    public Builder setStagingSchema(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      stagingSchema_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Schema in which gpss creates external and temp tables; default is to create these tables in the same schema as the target table
     * </pre>
     *
     * <code>string StagingSchema = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearStagingSchema() {
      stagingSchema_ = getDefaultInstance().getStagingSchema();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Schema in which gpss creates external and temp tables; default is to create these tables in the same schema as the target table
     * </pre>
     *
     * <code>string StagingSchema = 8;</code>
     * @param value The bytes for stagingSchema to set.
     * @return This builder for chaining.
     */
    public Builder setStagingSchemaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      stagingSchema_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.flink.connector.jdbc.table.sink.api.InsertOption, org.apache.flink.connector.jdbc.table.sink.api.InsertOption.Builder, org.apache.flink.connector.jdbc.table.sink.api.InsertOptionOrBuilder> insertOptionBuilder_;
    /**
     * <code>.api.InsertOption InsertOption = 100;</code>
     * @return Whether the insertOption field is set.
     */
    @java.lang.Override
    public boolean hasInsertOption() {
      return optionCase_ == 100;
    }
    /**
     * <code>.api.InsertOption InsertOption = 100;</code>
     * @return The insertOption.
     */
    @java.lang.Override
    public org.apache.flink.connector.jdbc.table.sink.api.InsertOption getInsertOption() {
      if (insertOptionBuilder_ == null) {
        if (optionCase_ == 100) {
          return (org.apache.flink.connector.jdbc.table.sink.api.InsertOption) option_;
        }
        return org.apache.flink.connector.jdbc.table.sink.api.InsertOption.getDefaultInstance();
      } else {
        if (optionCase_ == 100) {
          return insertOptionBuilder_.getMessage();
        }
        return org.apache.flink.connector.jdbc.table.sink.api.InsertOption.getDefaultInstance();
      }
    }
    /**
     * <code>.api.InsertOption InsertOption = 100;</code>
     */
    public Builder setInsertOption(org.apache.flink.connector.jdbc.table.sink.api.InsertOption value) {
      if (insertOptionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        option_ = value;
        onChanged();
      } else {
        insertOptionBuilder_.setMessage(value);
      }
      optionCase_ = 100;
      return this;
    }
    /**
     * <code>.api.InsertOption InsertOption = 100;</code>
     */
    public Builder setInsertOption(
        org.apache.flink.connector.jdbc.table.sink.api.InsertOption.Builder builderForValue) {
      if (insertOptionBuilder_ == null) {
        option_ = builderForValue.build();
        onChanged();
      } else {
        insertOptionBuilder_.setMessage(builderForValue.build());
      }
      optionCase_ = 100;
      return this;
    }
    /**
     * <code>.api.InsertOption InsertOption = 100;</code>
     */
    public Builder mergeInsertOption(org.apache.flink.connector.jdbc.table.sink.api.InsertOption value) {
      if (insertOptionBuilder_ == null) {
        if (optionCase_ == 100 &&
            option_ != org.apache.flink.connector.jdbc.table.sink.api.InsertOption.getDefaultInstance()) {
          option_ = org.apache.flink.connector.jdbc.table.sink.api.InsertOption.newBuilder((org.apache.flink.connector.jdbc.table.sink.api.InsertOption) option_)
              .mergeFrom(value).buildPartial();
        } else {
          option_ = value;
        }
        onChanged();
      } else {
        if (optionCase_ == 100) {
          insertOptionBuilder_.mergeFrom(value);
        } else {
          insertOptionBuilder_.setMessage(value);
        }
      }
      optionCase_ = 100;
      return this;
    }
    /**
     * <code>.api.InsertOption InsertOption = 100;</code>
     */
    public Builder clearInsertOption() {
      if (insertOptionBuilder_ == null) {
        if (optionCase_ == 100) {
          optionCase_ = 0;
          option_ = null;
          onChanged();
        }
      } else {
        if (optionCase_ == 100) {
          optionCase_ = 0;
          option_ = null;
        }
        insertOptionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.api.InsertOption InsertOption = 100;</code>
     */
    public org.apache.flink.connector.jdbc.table.sink.api.InsertOption.Builder getInsertOptionBuilder() {
      return getInsertOptionFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.InsertOption InsertOption = 100;</code>
     */
    @java.lang.Override
    public org.apache.flink.connector.jdbc.table.sink.api.InsertOptionOrBuilder getInsertOptionOrBuilder() {
      if ((optionCase_ == 100) && (insertOptionBuilder_ != null)) {
        return insertOptionBuilder_.getMessageOrBuilder();
      } else {
        if (optionCase_ == 100) {
          return (org.apache.flink.connector.jdbc.table.sink.api.InsertOption) option_;
        }
        return org.apache.flink.connector.jdbc.table.sink.api.InsertOption.getDefaultInstance();
      }
    }
    /**
     * <code>.api.InsertOption InsertOption = 100;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.flink.connector.jdbc.table.sink.api.InsertOption, org.apache.flink.connector.jdbc.table.sink.api.InsertOption.Builder, org.apache.flink.connector.jdbc.table.sink.api.InsertOptionOrBuilder> 
        getInsertOptionFieldBuilder() {
      if (insertOptionBuilder_ == null) {
        if (!(optionCase_ == 100)) {
          option_ = org.apache.flink.connector.jdbc.table.sink.api.InsertOption.getDefaultInstance();
        }
        insertOptionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.apache.flink.connector.jdbc.table.sink.api.InsertOption, org.apache.flink.connector.jdbc.table.sink.api.InsertOption.Builder, org.apache.flink.connector.jdbc.table.sink.api.InsertOptionOrBuilder>(
                (org.apache.flink.connector.jdbc.table.sink.api.InsertOption) option_,
                getParentForChildren(),
                isClean());
        option_ = null;
      }
      optionCase_ = 100;
      onChanged();
      return insertOptionBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.flink.connector.jdbc.table.sink.api.UpdateOption, org.apache.flink.connector.jdbc.table.sink.api.UpdateOption.Builder, org.apache.flink.connector.jdbc.table.sink.api.UpdateOptionOrBuilder> updateOptionBuilder_;
    /**
     * <code>.api.UpdateOption UpdateOption = 101;</code>
     * @return Whether the updateOption field is set.
     */
    @java.lang.Override
    public boolean hasUpdateOption() {
      return optionCase_ == 101;
    }
    /**
     * <code>.api.UpdateOption UpdateOption = 101;</code>
     * @return The updateOption.
     */
    @java.lang.Override
    public org.apache.flink.connector.jdbc.table.sink.api.UpdateOption getUpdateOption() {
      if (updateOptionBuilder_ == null) {
        if (optionCase_ == 101) {
          return (org.apache.flink.connector.jdbc.table.sink.api.UpdateOption) option_;
        }
        return org.apache.flink.connector.jdbc.table.sink.api.UpdateOption.getDefaultInstance();
      } else {
        if (optionCase_ == 101) {
          return updateOptionBuilder_.getMessage();
        }
        return org.apache.flink.connector.jdbc.table.sink.api.UpdateOption.getDefaultInstance();
      }
    }
    /**
     * <code>.api.UpdateOption UpdateOption = 101;</code>
     */
    public Builder setUpdateOption(org.apache.flink.connector.jdbc.table.sink.api.UpdateOption value) {
      if (updateOptionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        option_ = value;
        onChanged();
      } else {
        updateOptionBuilder_.setMessage(value);
      }
      optionCase_ = 101;
      return this;
    }
    /**
     * <code>.api.UpdateOption UpdateOption = 101;</code>
     */
    public Builder setUpdateOption(
        org.apache.flink.connector.jdbc.table.sink.api.UpdateOption.Builder builderForValue) {
      if (updateOptionBuilder_ == null) {
        option_ = builderForValue.build();
        onChanged();
      } else {
        updateOptionBuilder_.setMessage(builderForValue.build());
      }
      optionCase_ = 101;
      return this;
    }
    /**
     * <code>.api.UpdateOption UpdateOption = 101;</code>
     */
    public Builder mergeUpdateOption(org.apache.flink.connector.jdbc.table.sink.api.UpdateOption value) {
      if (updateOptionBuilder_ == null) {
        if (optionCase_ == 101 &&
            option_ != org.apache.flink.connector.jdbc.table.sink.api.UpdateOption.getDefaultInstance()) {
          option_ = org.apache.flink.connector.jdbc.table.sink.api.UpdateOption.newBuilder((org.apache.flink.connector.jdbc.table.sink.api.UpdateOption) option_)
              .mergeFrom(value).buildPartial();
        } else {
          option_ = value;
        }
        onChanged();
      } else {
        if (optionCase_ == 101) {
          updateOptionBuilder_.mergeFrom(value);
        } else {
          updateOptionBuilder_.setMessage(value);
        }
      }
      optionCase_ = 101;
      return this;
    }
    /**
     * <code>.api.UpdateOption UpdateOption = 101;</code>
     */
    public Builder clearUpdateOption() {
      if (updateOptionBuilder_ == null) {
        if (optionCase_ == 101) {
          optionCase_ = 0;
          option_ = null;
          onChanged();
        }
      } else {
        if (optionCase_ == 101) {
          optionCase_ = 0;
          option_ = null;
        }
        updateOptionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.api.UpdateOption UpdateOption = 101;</code>
     */
    public org.apache.flink.connector.jdbc.table.sink.api.UpdateOption.Builder getUpdateOptionBuilder() {
      return getUpdateOptionFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.UpdateOption UpdateOption = 101;</code>
     */
    @java.lang.Override
    public org.apache.flink.connector.jdbc.table.sink.api.UpdateOptionOrBuilder getUpdateOptionOrBuilder() {
      if ((optionCase_ == 101) && (updateOptionBuilder_ != null)) {
        return updateOptionBuilder_.getMessageOrBuilder();
      } else {
        if (optionCase_ == 101) {
          return (org.apache.flink.connector.jdbc.table.sink.api.UpdateOption) option_;
        }
        return org.apache.flink.connector.jdbc.table.sink.api.UpdateOption.getDefaultInstance();
      }
    }
    /**
     * <code>.api.UpdateOption UpdateOption = 101;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.flink.connector.jdbc.table.sink.api.UpdateOption, org.apache.flink.connector.jdbc.table.sink.api.UpdateOption.Builder, org.apache.flink.connector.jdbc.table.sink.api.UpdateOptionOrBuilder> 
        getUpdateOptionFieldBuilder() {
      if (updateOptionBuilder_ == null) {
        if (!(optionCase_ == 101)) {
          option_ = org.apache.flink.connector.jdbc.table.sink.api.UpdateOption.getDefaultInstance();
        }
        updateOptionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.apache.flink.connector.jdbc.table.sink.api.UpdateOption, org.apache.flink.connector.jdbc.table.sink.api.UpdateOption.Builder, org.apache.flink.connector.jdbc.table.sink.api.UpdateOptionOrBuilder>(
                (org.apache.flink.connector.jdbc.table.sink.api.UpdateOption) option_,
                getParentForChildren(),
                isClean());
        option_ = null;
      }
      optionCase_ = 101;
      onChanged();
      return updateOptionBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.flink.connector.jdbc.table.sink.api.MergeOption, org.apache.flink.connector.jdbc.table.sink.api.MergeOption.Builder, org.apache.flink.connector.jdbc.table.sink.api.MergeOptionOrBuilder> mergeOptionBuilder_;
    /**
     * <code>.api.MergeOption MergeOption = 102;</code>
     * @return Whether the mergeOption field is set.
     */
    @java.lang.Override
    public boolean hasMergeOption() {
      return optionCase_ == 102;
    }
    /**
     * <code>.api.MergeOption MergeOption = 102;</code>
     * @return The mergeOption.
     */
    @java.lang.Override
    public org.apache.flink.connector.jdbc.table.sink.api.MergeOption getMergeOption() {
      if (mergeOptionBuilder_ == null) {
        if (optionCase_ == 102) {
          return (org.apache.flink.connector.jdbc.table.sink.api.MergeOption) option_;
        }
        return org.apache.flink.connector.jdbc.table.sink.api.MergeOption.getDefaultInstance();
      } else {
        if (optionCase_ == 102) {
          return mergeOptionBuilder_.getMessage();
        }
        return org.apache.flink.connector.jdbc.table.sink.api.MergeOption.getDefaultInstance();
      }
    }
    /**
     * <code>.api.MergeOption MergeOption = 102;</code>
     */
    public Builder setMergeOption(org.apache.flink.connector.jdbc.table.sink.api.MergeOption value) {
      if (mergeOptionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        option_ = value;
        onChanged();
      } else {
        mergeOptionBuilder_.setMessage(value);
      }
      optionCase_ = 102;
      return this;
    }
    /**
     * <code>.api.MergeOption MergeOption = 102;</code>
     */
    public Builder setMergeOption(
        org.apache.flink.connector.jdbc.table.sink.api.MergeOption.Builder builderForValue) {
      if (mergeOptionBuilder_ == null) {
        option_ = builderForValue.build();
        onChanged();
      } else {
        mergeOptionBuilder_.setMessage(builderForValue.build());
      }
      optionCase_ = 102;
      return this;
    }
    /**
     * <code>.api.MergeOption MergeOption = 102;</code>
     */
    public Builder mergeMergeOption(org.apache.flink.connector.jdbc.table.sink.api.MergeOption value) {
      if (mergeOptionBuilder_ == null) {
        if (optionCase_ == 102 &&
            option_ != org.apache.flink.connector.jdbc.table.sink.api.MergeOption.getDefaultInstance()) {
          option_ = org.apache.flink.connector.jdbc.table.sink.api.MergeOption.newBuilder((org.apache.flink.connector.jdbc.table.sink.api.MergeOption) option_)
              .mergeFrom(value).buildPartial();
        } else {
          option_ = value;
        }
        onChanged();
      } else {
        if (optionCase_ == 102) {
          mergeOptionBuilder_.mergeFrom(value);
        } else {
          mergeOptionBuilder_.setMessage(value);
        }
      }
      optionCase_ = 102;
      return this;
    }
    /**
     * <code>.api.MergeOption MergeOption = 102;</code>
     */
    public Builder clearMergeOption() {
      if (mergeOptionBuilder_ == null) {
        if (optionCase_ == 102) {
          optionCase_ = 0;
          option_ = null;
          onChanged();
        }
      } else {
        if (optionCase_ == 102) {
          optionCase_ = 0;
          option_ = null;
        }
        mergeOptionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.api.MergeOption MergeOption = 102;</code>
     */
    public org.apache.flink.connector.jdbc.table.sink.api.MergeOption.Builder getMergeOptionBuilder() {
      return getMergeOptionFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.MergeOption MergeOption = 102;</code>
     */
    @java.lang.Override
    public org.apache.flink.connector.jdbc.table.sink.api.MergeOptionOrBuilder getMergeOptionOrBuilder() {
      if ((optionCase_ == 102) && (mergeOptionBuilder_ != null)) {
        return mergeOptionBuilder_.getMessageOrBuilder();
      } else {
        if (optionCase_ == 102) {
          return (org.apache.flink.connector.jdbc.table.sink.api.MergeOption) option_;
        }
        return org.apache.flink.connector.jdbc.table.sink.api.MergeOption.getDefaultInstance();
      }
    }
    /**
     * <code>.api.MergeOption MergeOption = 102;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.flink.connector.jdbc.table.sink.api.MergeOption, org.apache.flink.connector.jdbc.table.sink.api.MergeOption.Builder, org.apache.flink.connector.jdbc.table.sink.api.MergeOptionOrBuilder> 
        getMergeOptionFieldBuilder() {
      if (mergeOptionBuilder_ == null) {
        if (!(optionCase_ == 102)) {
          option_ = org.apache.flink.connector.jdbc.table.sink.api.MergeOption.getDefaultInstance();
        }
        mergeOptionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.apache.flink.connector.jdbc.table.sink.api.MergeOption, org.apache.flink.connector.jdbc.table.sink.api.MergeOption.Builder, org.apache.flink.connector.jdbc.table.sink.api.MergeOptionOrBuilder>(
                (org.apache.flink.connector.jdbc.table.sink.api.MergeOption) option_,
                getParentForChildren(),
                isClean());
        option_ = null;
      }
      optionCase_ = 102;
      onChanged();
      return mergeOptionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.OpenRequest)
  }

  // @@protoc_insertion_point(class_scope:api.OpenRequest)
  private static final org.apache.flink.connector.jdbc.table.sink.api.OpenRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.apache.flink.connector.jdbc.table.sink.api.OpenRequest();
  }

  public static org.apache.flink.connector.jdbc.table.sink.api.OpenRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OpenRequest>
      PARSER = new com.google.protobuf.AbstractParser<OpenRequest>() {
    @java.lang.Override
    public OpenRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<OpenRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OpenRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.apache.flink.connector.jdbc.table.sink.api.OpenRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

