// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adbpgss.proto

package org.apache.flink.connector.jdbc.table.sink.api;

public interface ReadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.ReadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Data = 1;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string Data = 1;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
