// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adbpgss.proto

package org.apache.flink.connector.jdbc.table.sink.api;

public interface ReadOptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.ReadOption)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string MagicCode = 1;</code>
   * @return The magicCode.
   */
  java.lang.String getMagicCode();
  /**
   * <code>string MagicCode = 1;</code>
   * @return The bytes for magicCode.
   */
  com.google.protobuf.ByteString
      getMagicCodeBytes();
}
