// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adbpgss.proto

package org.apache.flink.connector.jdbc.table.sink.api;

public interface RowOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.Row)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .api.DBValue Columns = 1;</code>
   */
  java.util.List<org.apache.flink.connector.jdbc.table.sink.api.DBValue> 
      getColumnsList();
  /**
   * <code>repeated .api.DBValue Columns = 1;</code>
   */
  org.apache.flink.connector.jdbc.table.sink.api.DBValue getColumns(int index);
  /**
   * <code>repeated .api.DBValue Columns = 1;</code>
   */
  int getColumnsCount();
  /**
   * <code>repeated .api.DBValue Columns = 1;</code>
   */
  java.util.List<? extends org.apache.flink.connector.jdbc.table.sink.api.DBValueOrBuilder> 
      getColumnsOrBuilderList();
  /**
   * <code>repeated .api.DBValue Columns = 1;</code>
   */
  org.apache.flink.connector.jdbc.table.sink.api.DBValueOrBuilder getColumnsOrBuilder(
      int index);
}
