// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adbpgss.proto

package org.apache.flink.connector.jdbc.table.sink.api;

public interface SchemasOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.Schemas)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .api.Schema Schemas = 1;</code>
   */
  java.util.List<org.apache.flink.connector.jdbc.table.sink.api.Schema> 
      getSchemasList();
  /**
   * <code>repeated .api.Schema Schemas = 1;</code>
   */
  org.apache.flink.connector.jdbc.table.sink.api.Schema getSchemas(int index);
  /**
   * <code>repeated .api.Schema Schemas = 1;</code>
   */
  int getSchemasCount();
  /**
   * <code>repeated .api.Schema Schemas = 1;</code>
   */
  java.util.List<? extends org.apache.flink.connector.jdbc.table.sink.api.SchemaOrBuilder> 
      getSchemasOrBuilderList();
  /**
   * <code>repeated .api.Schema Schemas = 1;</code>
   */
  org.apache.flink.connector.jdbc.table.sink.api.SchemaOrBuilder getSchemasOrBuilder(
      int index);
}
