// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package org.apache.flink.connector.jdbc.table.sink.api;

public interface TransferStatsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.TransferStats)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Number of rows successfully loaded
   * </pre>
   *
   * <code>int64 SuccessCount = 1;</code>
   * @return The successCount.
   */
  long getSuccessCount();

  /**
   * <pre>
   * Number of error lines if Errorlimit is not reached
   * </pre>
   *
   * <code>int64 ErrorCount = 2;</code>
   * @return The errorCount.
   */
  long getErrorCount();

  /**
   * <pre>
   * Number of rows with incorrectly-formatted data; not supported
   * </pre>
   *
   * <code>repeated string ErrorRows = 3;</code>
   * @return A list containing the errorRows.
   */
  java.util.List<String>
      getErrorRowsList();
  /**
   * <pre>
   * Number of rows with incorrectly-formatted data; not supported
   * </pre>
   *
   * <code>repeated string ErrorRows = 3;</code>
   * @return The count of errorRows.
   */
  int getErrorRowsCount();
  /**
   * <pre>
   * Number of rows with incorrectly-formatted data; not supported
   * </pre>
   *
   * <code>repeated string ErrorRows = 3;</code>
   * @param index The index of the element to return.
   * @return The errorRows at the given index.
   */
  String getErrorRows(int index);
  /**
   * <pre>
   * Number of rows with incorrectly-formatted data; not supported
   * </pre>
   *
   * <code>repeated string ErrorRows = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the errorRows at the given index.
   */
  com.google.protobuf.ByteString
      getErrorRowsBytes(int index);
}
