// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adbpgss.proto

package org.apache.flink.connector.jdbc.table.sink.api;

public interface WriteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.WriteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api.Session Session = 1;</code>
   * @return Whether the session field is set.
   */
  boolean hasSession();
  /**
   * <code>.api.Session Session = 1;</code>
   * @return The session.
   */
  org.apache.flink.connector.jdbc.table.sink.api.Session getSession();
  /**
   * <code>.api.Session Session = 1;</code>
   */
  org.apache.flink.connector.jdbc.table.sink.api.SessionOrBuilder getSessionOrBuilder();

  /**
   * <pre>
   * The data to load into the target table
   * </pre>
   *
   * <code>repeated .api.RowData Rows = 2;</code>
   */
  java.util.List<org.apache.flink.connector.jdbc.table.sink.api.RowData> 
      getRowsList();
  /**
   * <pre>
   * The data to load into the target table
   * </pre>
   *
   * <code>repeated .api.RowData Rows = 2;</code>
   */
  org.apache.flink.connector.jdbc.table.sink.api.RowData getRows(int index);
  /**
   * <pre>
   * The data to load into the target table
   * </pre>
   *
   * <code>repeated .api.RowData Rows = 2;</code>
   */
  int getRowsCount();
  /**
   * <pre>
   * The data to load into the target table
   * </pre>
   *
   * <code>repeated .api.RowData Rows = 2;</code>
   */
  java.util.List<? extends org.apache.flink.connector.jdbc.table.sink.api.RowDataOrBuilder> 
      getRowsOrBuilderList();
  /**
   * <pre>
   * The data to load into the target table
   * </pre>
   *
   * <code>repeated .api.RowData Rows = 2;</code>
   */
  org.apache.flink.connector.jdbc.table.sink.api.RowDataOrBuilder getRowsOrBuilder(
      int index);
}
